name: Test

on:
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

  pull_request:
    types: [opened, reopened, synchronize]
  release:
    types: [published]
    tags:
      - "v*.*.*"

jobs:
  linux:
    name: Run action
    runs-on: ${{ matrix.operating-systems }}
    strategy:
      matrix:
        operating-systems: [
            ubuntu-latest
            #windows-latest,
            # macos-latest
          ]

        amxmodx: ['1.10']

    steps:
      - uses: actions/checkout@v2

      - name: Setup AMXXPawn Compiler
        uses: wopox1337/setup-amxxpawn@master
        with:
          version: ${{ matrix.amxmodx }}

      - name: Compile
        shell: bash
        run: |
          sudo mkdir ${{ github.workspace }}/res/addons/amxmodx/plugins
          amxxpc src/bomberman_mod.sma -i"$includePath" -o"src/bomberman_mod.amxx"
      
      - name: Move compiled plugin
        run: |
          sudo mv ${{ github.workspace }}/src/bomberman_mod.amxx ${{ github.workspace }}/res/addons/amxmodx/plugins/bomberman_mod.amxx
          7z a -tzip resources ${{ github.workspace }}/res/
          
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
          name: resources.zip
          path: resources.zip
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    needs: [linux]
    
    steps:
      - name: Deploying linux artifacts
        uses: actions/download-artifact@v2
        with:
          name: resources.zip
        
      - name: Publish artifacts
        uses: softprops/action-gh-release@v1
        id: publish-job
        if: |
          startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.zip
            *.7z
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
